// Diccionario de nombres — LÉXICO, no personas.
//
// Aclaración que importa en un repo público con la regla "jamás un dato real": esto es una lista de
// PALABRAS (nombres de pila y apellidos de uso corriente en Colombia), del mismo tipo que un
// diccionario de idioma. No describe a nadie, no proviene de ningún registro y ninguna combinación
// aquí corresponde a una persona concreta.
//
// Es también el único validador del motor que reconoce por vocabulario en vez de por algoritmo, y
// por eso es ESTRUCTURAL con una limitación declarada: reconoce lo frecuente y se le escapa lo
// infrecuente. Un apellido poco común no deja de ser un apellido porque no esté en esta lista — por
// eso el clasificador combina esta señal con el nombre de la columna en vez de depender solo de ella.

import type { Validador } from "../validadores/tipos";

/** Quita tildes y pasa a minúsculas para que "MARÍA", "maria" y "María" sean el mismo token. */
export function normalizarToken(texto: string): string {
  return texto.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
}

const NOMBRES_DE_PILA = [
  "alejandro",
  "alberto",
  "alfonso",
  "alicia",
  "amparo",
  "ana",
  "andrea",
  "andres",
  "angela",
  "antonio",
  "beatriz",
  "camila",
  "carlos",
  "carmen",
  "catalina",
  "cecilia",
  "cesar",
  "claudia",
  "clara",
  "cristian",
  "cristina",
  "daniel",
  "daniela",
  "david",
  "diana",
  "diego",
  "dora",
  "eduardo",
  "elena",
  "elizabeth",
  "emilio",
  "enrique",
  "esperanza",
  "esteban",
  "fabian",
  "felipe",
  "fernando",
  "flor",
  "francisco",
  "gabriel",
  "gabriela",
  "german",
  "gloria",
  "gustavo",
  "hector",
  "helena",
  "henry",
  "hernan",
  "hugo",
  "ignacio",
  "ines",
  "isabel",
  "isabela",
  "ivan",
  "javier",
  "jaime",
  "jorge",
  "jose",
  "juan",
  "juliana",
  "julio",
  "karen",
  "laura",
  "leonardo",
  "leidy",
  "lina",
  "lucia",
  "luis",
  "luisa",
  "luz",
  "manuel",
  "marcela",
  "margarita",
  "maria",
  "mariana",
  "mario",
  "marta",
  "mateo",
  "mauricio",
  "miguel",
  "monica",
  "natalia",
  "nelson",
  "nicolas",
  "norma",
  "olga",
  "oscar",
  "pablo",
  "paola",
  "patricia",
  "paula",
  "pedro",
  "rafael",
  "ramiro",
  "raul",
  "ricardo",
  "roberto",
  "rocio",
  "rodrigo",
  "rosa",
  "ruben",
  "ruth",
  "samuel",
  "sandra",
  "santiago",
  "sara",
  "sebastian",
  "sergio",
  "silvia",
  "sofia",
  "sonia",
  "tatiana",
  "teresa",
  "tomas",
  "valentina",
  "vanessa",
  "veronica",
  "victor",
  "victoria",
  "wilson",
  "ximena",
  "yolanda",
  "yuly",
];

const APELLIDOS = [
  "acosta",
  "agudelo",
  "aguilar",
  "alvarez",
  "arango",
  "arias",
  "avila",
  "ayala",
  "bautista",
  "bedoya",
  "benitez",
  "bermudez",
  "betancur",
  "bonilla",
  "buitrago",
  "caicedo",
  "calderon",
  "camacho",
  "cano",
  "cardenas",
  "cardona",
  "carvajal",
  "castaño",
  "castillo",
  "castro",
  "cifuentes",
  "contreras",
  "cordoba",
  "correa",
  "cortes",
  "cruz",
  "delgado",
  "diaz",
  "duarte",
  "duque",
  "echeverri",
  "escobar",
  "espinosa",
  "estrada",
  "fernandez",
  "flores",
  "forero",
  "franco",
  "galeano",
  "gallego",
  "garcia",
  "garzon",
  "gil",
  "giraldo",
  "gomez",
  "gonzalez",
  "granados",
  "guerrero",
  "gutierrez",
  "guzman",
  "henao",
  "heredia",
  "hernandez",
  "herrera",
  "hoyos",
  "hurtado",
  "ibarra",
  "jaramillo",
  "jimenez",
  "lara",
  "leon",
  "lopez",
  "lozano",
  "luna",
  "macias",
  "maldonado",
  "marin",
  "martinez",
  "medina",
  "mejia",
  "mendez",
  "mendoza",
  "molina",
  "montoya",
  "mora",
  "morales",
  "moreno",
  "muñoz",
  "murillo",
  "narvaez",
  "navarro",
  "nieto",
  "niño",
  "ochoa",
  "ojeda",
  "olaya",
  "ordoñez",
  "orozco",
  "ortega",
  "ortiz",
  "osorio",
  "ospina",
  "otalora",
  "pabon",
  "pacheco",
  "padilla",
  "palacios",
  "pardo",
  "parra",
  "patiño",
  "peña",
  "perez",
  "pineda",
  "pinzon",
  "posada",
  "prieto",
  "puentes",
  "quintero",
  "quiroga",
  "ramirez",
  "ramos",
  "restrepo",
  "reyes",
  "rincon",
  "rios",
  "rivas",
  "rivera",
  "robayo",
  "rodriguez",
  "rojas",
  "roldan",
  "romero",
  "rueda",
  "ruiz",
  "salazar",
  "salinas",
  "sanabria",
  "sanchez",
  "sandoval",
  "santamaria",
  "sepulveda",
  "serrano",
  "sierra",
  "silva",
  "solano",
  "soto",
  "suarez",
  "tamayo",
  "tellez",
  "toro",
  "torres",
  "trujillo",
  "urrego",
  "valencia",
  "valderrama",
  "vanegas",
  "vargas",
  "vasquez",
  "velasquez",
  "vera",
  "villamil",
  "villegas",
  "zapata",
  "zuluaga",
];

const LEXICO = new Set([...NOMBRES_DE_PILA, ...APELLIDOS]);

/** Partículas que unen apellidos compuestos ("de la Torre") y no cuentan como token con carga. */
const PARTICULAS = new Set([
  "de",
  "del",
  "la",
  "las",
  "los",
  "y",
  "san",
  "santa",
]);

/** ¿Es un nombre propio de persona? Expuesto aparte para que los tests lo usen sin el validador. */
export function pareceNombreDePersona(valor: string): boolean {
  const limpio = valor.trim();
  if (limpio.length < 3 || limpio.length > 80) return false;
  // Solo letras (con tildes y ñ), espacios, apóstrofos y guiones: un nombre no lleva dígitos.
  if (!/^[\p{L}][\p{L}\s'’-]*$/u.test(limpio)) return false;

  const tokens = limpio.split(/\s+/).map(normalizarToken);
  if (tokens.length < 1 || tokens.length > 6) return false;

  const conCarga = tokens.filter((t) => !PARTICULAS.has(t));
  if (conCarga.length === 0) return false;
  return conCarga.some((token) => LEXICO.has(token));
}

export const validadorNombre: Validador = {
  id: "nombre",
  etiqueta: "Nombre de persona",
  fuente:
    "Diccionario de nombres y apellidos de uso corriente en Colombia (léxico, no registro de " +
    "personas). Reconoce lo frecuente; lo infrecuente se le escapa, y por eso el clasificador " +
    "combina esta señal con el nombre de la columna.",
  certeza: "estructural",
  categoria: "identificador-directo",
  prioridad: 65,
  valida: (valor) => pareceNombreDePersona(valor),
};
